### ISSUE TITLE
multipe camera tracking

### ISSUE THREAD

**Issue by hispavista** [incluit/OpenVino-For-SmartCity#2]
Hi!
Would it be possible to use this example to track pedestrians with multiple cameras?
If not, some idea of what should be changed?
Thank you,

**Comment by Mauroabbatemarco** [comment]
Please elaborate further on your comment! Are you using an stereo camera? Or you want to reidentify and keep tracking a pedestrian with multiple cameras that are near and share the same sight?

**Comment by hispavista** [comment]
I am using multiple cameras and i want to reidentify the same person in both cameras and count one time

**Comment by Mauroabbatemarco** [comment]
**That case scenario is out of the scope of this project.** 
Nevertheless, if the cameras share the field of view, I think you could count once over a single person. I would run the inference process in both camera feeds, and would perform a feature description + matching process with the image inside each ROI.
