### ISSUE TITLE
I want to generate new detection model

### ISSUE THREAD

**Issue by user-redans** [incluit/OpenVino-For-SmartCity#6]
Hi,
In Ubuntu x64,  v. 16_04, I run successfully this demo and worked perfectly, using CPU. Now I want to detect another thinghs like coins or bulbs or ..... something else, not just cars or pedestrian.  I don't know how to create and assing a new trained model to this demo. Any suggestions?  What should I use for this TensorFlow, Caffe or Yolo alg. ?

**Comment by HernanG234** [comment]
Hi there!

You can use any of these but you'll have to read a bit on how to use Intel's OpenVino Model Optimizer. I'm sorry I can't provide you the links as I'm travelling but a quick Google search on this should be enough. After that you should get a bin and a .xml of your model and load it using OpenVino's toolkit.

If you have questions about openvino's implementation, it may be better to ask directly on Intel's forum.

Good luck! Keep us posted on your project :).

Cheers!
