### ISSUE TITLE
[VPU] Unsupported network precision : FP32

### ISSUE THREAD

**Issue by user-redans** [incluit/OpenVino-For-SmartCity#7]
Hi,
I recently bought NCS2 from Intel Movidius Myriad X VPU and I follow all steps from [this ](https://software.intel.com/en-us/articles/get-started-with-neural-compute-stick) tutorial on Linux guest (WIN10 host). 

Linux guest distribution:
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.6 LTS
Release:	16.04
Codename:	xenial

All steps works fine, even step 4, where installation is testead.

My problem is when I using this script, with MYRIAD parameter (instead, with CPU it works).

./intel64/Release/smart_city_tutorial -m_vp $vehicle232 -d_vp MYRIAD -i ../data/NewVideo2.mp4

This is my console result:

root@ubuntu:/home/redans/tutorials/OpenVino-For-SmartCity/OpenVino-For-SmartCity/build# ./intel64/Release/smart_city_tutorial -m_vp $vehicle232 -d_vp MYRIAD -i ../data/NewVideo2.mp4
Incluit - Openvino-for-Smartcity
[VPU] Unsupported network precision : FP32
If missing -d_y argument, try running ../scripts/setupenv.sh

Do you have any suggestions?

**Comment by user-redans** [comment]
Update: Intel Movidius Myriad X VPU does not support FP32 precision. So I have to use FP16 or other supported precision. How can I do that? How can I change this precision?

**Comment by flaviojpriotti** [comment]
Hi @user-redans, thanks for use our project!

What you say is correct, Intel Movidius Myriad X VPU does not support FP32 precision, you need to use FP16.

You could try run the FP16 model: https://github.com/incluit/OpenVino-For-SmartCity#other-models

In your case, try with -m_vp $vehicle2**16**:
`./intel64/Release/smart_city_tutorial -m_vp $vehicle216 -d_vp MYRIAD -i ../data/NewVideo2.mp4`

Please, you don't forget source the enviorment variables:
`source ../scripts/setupenv.sh`

Please, let us know if you can run the program!

Regards, Flavio.

**Comment by user-redans** [comment]
Thanks for advices! It's works !

**Comment by user-redans** [comment]
Now, that it works I want to train another detection model, for example to detect eggs or bulbs or I don't know... something else. It's posible to do that and after could I integreated it into this tutorial?

**Comment by flaviojpriotti** [comment]
Hi @user-redans, our program consists on showcasing the advantages of the Intel’s OpenVINO toolkit, in this case the models for vehicle and pedestrian detection.
OpenVino is not intended for training models, rather to be used with pre-trained models. 

Anyway, you could try it! If you do, tell us the results!

Regards, Flavio.
