### ISSUE TITLE
How can I re-train a model?

### ISSUE THREAD

**Issue by user-redans** [incluit/OpenVino-For-SmartCity#8]
Hi,
I recently bought NCS2 from Intel Movidius Myriad X VPU and I tried [this ](https://github.com/incluit/OpenVino-For-SmartCity)demo on Linux guest (WIN10 host).

Linux guest distribution:
Distributor ID: Ubuntu
Description: Ubuntu 16.04.6 LTS
Release: 16.04
Codename: xenial

All examples woks fine. Now, I want to train another detection model, for example to detect eggs or bulbs or I don't know... something else. It's posible to do that and after could I integreated it into this tutorial?

**Comment by flaviojpriotti** [comment]
Hi @user-redans, our program consists on showcasing the advantages of the Intel’s OpenVINO toolkit, in this case the models for vehicle and pedestrian detection.
OpenVino is not intended for training models, rather to be used with pre-trained models. 

Anyway, you could try it! If you do, tell us the results!

Regards, Flavio.

**Comment by user-redans** [comment]
Hi Flavio,
Thanks for info's! I know that OpenVINO is not using for training, for that are TensorFlow, Caffe etc. I was interested if I can used this demo after I trained a new model with TensorFlow or Caffe.

**Comment by flaviojpriotti** [comment]
Hi @user-redans, we can not assure you that it works. But, you don't hesitate to try it. If you get satisfactory results, please let us know!

Regards, Flavio.

**Comment by Gowtham171996** [comment]
If someone is on this path. This link may be usefull: [https://github.com/vijnasu/TF-Training-OpenVINO-Inference](https://github.com/vijnasu/TF-Training-OpenVINO-Inference)
